const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    title: 'Recipe Manager API',
    description: 'API for managing recipes with comprehensive validation and error handling',
    version: '1.0.0',
    contact: {
      email: 'recipe-api@example.com'
    },
    license: {
      name: 'MIT',
      url: 'https://opensource.org/licenses/MIT'
    }
  },
  host: process.env.HOST || 'recipe-cse341.onrender.com' || 'localhost:3000',
  schemes: ['https', 'http'],
  basePath: '/',
  tags: [
    {
      name: 'recipes',
      description: 'Operations about recipes'
    },
    {
      name: 'premium-recipes',
      description: 'Operations about premium recipes (requires Google OAuth authentication)'
    }
  ],
  definitions: {
    Recipe: {
      type: 'object',
      properties: {
        _id: {
          type: 'string',
          description: 'Recipe ID (auto-generated by MongoDB)',
          example: '507f1f77bcf86cd799439011'
        },
        name: {
          type: 'string',
          description: 'Recipe name (3-200 characters, cannot be only whitespace)',
          minLength: 3,
          maxLength: 200,
          example: 'Chocolate Chip Cookies'
        },
        servings: {
          type: 'integer',
          description: 'Number of servings',
          minimum: 1,
          maximum: 100,
          example: 12
        },
        prepMinutes: {
          type: 'integer',
          description: 'Preparation time in minutes',
          minimum: 0,
          maximum: 1440,
          example: 15
        },
        cookMinutes: {
          type: 'integer',
          description: 'Cooking time in minutes',
          minimum: 0,
          maximum: 1440,
          example: 10
        },
        ingredients: {
          type: 'array',
          description: 'List of ingredients',
          minItems: 1,
          items: {
            $ref: '#/definitions/Ingredient'
          }
        },
        steps: {
          type: 'array',
          description: 'Cooking instructions (each step 3-1000 characters, cannot be only whitespace)',
          minItems: 1,
          items: {
            type: 'string',
            minLength: 3,
            maxLength: 1000
          },
          example: ['Mix all dry ingredients in a large bowl', 'Add wet ingredients and mix until combined']
        }
      },
      required: ['_id', 'name', 'servings', 'prepMinutes', 'ingredients', 'steps']
    },
    Ingredient: {
      type: 'object',
      properties: {
        item: {
          type: 'string',
          description: 'Ingredient name (1-100 characters)',
          minLength: 1,
          maxLength: 100,
          example: 'flour'
        },
        quantity: {
          type: 'string',
          description: 'Ingredient quantity (1-50 characters, must be positive, cannot be zero, negative, or only whitespace)',
          minLength: 1,
          maxLength: 50,
          example: '2 cups'
        },
        notes: {
          type: 'string',
          description: 'Additional notes (optional, max 200 characters, empty strings are automatically removed)',
          maxLength: 200,
          example: 'sifted'
        },
        optional: {
          type: 'boolean',
          description: 'Whether ingredient is optional',
          example: false
        }
      },
      required: ['item', 'quantity']
    }
  }
};

const outputFile = './swagger.json';
const endpointsFiles = ['./routes/index.js', './routes/recipes.js', './routes/premiumRecipes.js'];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  // Post-process to add missing parameters and fix definitions
  const fs = require('fs');
  const swaggerDoc = JSON.parse(fs.readFileSync(outputFile, 'utf8'));
  
  // Remove erroneous POST endpoint from root path
  if (swaggerDoc.paths['/'] && swaggerDoc.paths['/'].post) {
    delete swaggerDoc.paths['/'].post;
  }
  
  // Remove erroneous generic /{id} path
  if (swaggerDoc.paths['/{id}']) {
    delete swaggerDoc.paths['/{id}'];
  }
  
  // Add tags to all recipe endpoints
  const recipePaths = ['/recipes/', '/recipes/{id}'];
  recipePaths.forEach(path => {
    if (swaggerDoc.paths[path]) {
      Object.keys(swaggerDoc.paths[path]).forEach(method => {
        if (!swaggerDoc.paths[path][method].tags) {
          swaggerDoc.paths[path][method].tags = ['recipes'];
        }
      });
    }
  });
  
  // Add POST body parameter
  if (swaggerDoc.paths['/recipes/'] && swaggerDoc.paths['/recipes/'].post) {
    swaggerDoc.paths['/recipes/'].post.parameters = [
      {
        name: 'body',
        in: 'body',
        required: true,
        schema: {
          $ref: '#/definitions/Recipe'
        }
      }
    ];
  }
  
  // Add PUT body parameter (append to existing path parameter)
  if (swaggerDoc.paths['/recipes/{id}'] && swaggerDoc.paths['/recipes/{id}'].put) {
    if (!swaggerDoc.paths['/recipes/{id}'].put.parameters) {
      swaggerDoc.paths['/recipes/{id}'].put.parameters = [];
    }
    // Only add body parameter if it doesn't already exist
    const hasBodyParam = swaggerDoc.paths['/recipes/{id}'].put.parameters.some(p => p.in === 'body');
    if (!hasBodyParam) {
      swaggerDoc.paths['/recipes/{id}'].put.parameters.push({
        name: 'body',
        in: 'body',
        required: true,
        schema: {
          $ref: '#/definitions/Recipe'
        }
      });
    }
  }
  
  // Add OAuth2 security definitions (Swagger 2.0 format)
  // Using implicit flow for Swagger UI (browser-based, no client secret needed)
  swaggerDoc.securityDefinitions = {
    googleOAuth: {
      type: 'oauth2',
      authorizationUrl: 'https://accounts.google.com/o/oauth2/auth',
      flow: 'implicit',
      scopes: {
        'https://www.googleapis.com/auth/userinfo.profile': 'Access profile information',
        'https://www.googleapis.com/auth/userinfo.email': 'Access email address'
      }
    }
  };
  
  // Apply security and tags to all premium-recipes endpoints
  const premiumRecipePaths = [
    '/premium-recipes/',
    '/premium-recipes/{id}'
  ];
  
  premiumRecipePaths.forEach(path => {
    if (swaggerDoc.paths[path]) {
      Object.keys(swaggerDoc.paths[path]).forEach(method => {
        // Add tags
        if (!swaggerDoc.paths[path][method].tags) {
          swaggerDoc.paths[path][method].tags = ['premium-recipes'];
        }
        // Add security
        if (!swaggerDoc.paths[path][method].security) {
          swaggerDoc.paths[path][method].security = [];
        }
        // Add OAuth2 security requirement if not already present
        const hasOAuth = swaggerDoc.paths[path][method].security.some(
          sec => sec.googleOAuth !== undefined
        );
        if (!hasOAuth) {
          swaggerDoc.paths[path][method].security.push({
            googleOAuth: ['https://www.googleapis.com/auth/userinfo.profile', 'https://www.googleapis.com/auth/userinfo.email']
          });
        }
      });
    }
  });
  
  // Remove POST, PUT, and DELETE methods from premium-recipes endpoints (only GET is allowed)
  if (swaggerDoc.paths['/premium-recipes/']) {
    delete swaggerDoc.paths['/premium-recipes/'].post;
    delete swaggerDoc.paths['/premium-recipes/'].put;
    delete swaggerDoc.paths['/premium-recipes/'].delete;
  }
  if (swaggerDoc.paths['/premium-recipes/{id}']) {
    delete swaggerDoc.paths['/premium-recipes/{id}'].post;
    delete swaggerDoc.paths['/premium-recipes/{id}'].put;
    delete swaggerDoc.paths['/premium-recipes/{id}'].delete;
  }
  
  // Write the corrected swagger.json
  fs.writeFileSync(outputFile, JSON.stringify(swaggerDoc, null, 2));
  console.log('Swagger documentation generated successfully with clean definitions and OAuth2 security');
});
